
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.io.File;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sonhy
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    String memberType = null;
    int bit = 0;
    
    public MainFrame() {
        initComponents();
    }

    private void interestBit(int b) {
        bit += b;
    }
    
    private void clear() {
        txtId.setText("");
        txtPw.setText("");
        txtPwConfirm.setText("");
        txtName.setText("");
        bit = 0;
        rbtnRegularMember.setSelected(true);
        rbtnAssociateMember.setSelected(false);
        rbtnStudentMember.setSelected(false);
        chkSwim.setSelected(false);
        chkGame.setSelected(false);
        chkGolf.setSelected(false);
        chkSki.setSelected(false);
        chkRead.setSelected(false);
        chkTennis.setSelected(false);
        lstPay.setSelectedIndex(0);
        cmbJob.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        lblPwConfirm = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();
        txtPw = new javax.swing.JPasswordField();
        txtPwConfirm = new javax.swing.JPasswordField();
        lblMemberType = new javax.swing.JLabel();
        rbtnRegularMember = new javax.swing.JRadioButton();
        rbtnAssociateMember = new javax.swing.JRadioButton();
        rbtnStudentMember = new javax.swing.JRadioButton();
        lblInterest = new javax.swing.JLabel();
        chkSwim = new javax.swing.JCheckBox();
        chkGame = new javax.swing.JCheckBox();
        chkGolf = new javax.swing.JCheckBox();
        chkSki = new javax.swing.JCheckBox();
        chkRead = new javax.swing.JCheckBox();
        chkTennis = new javax.swing.JCheckBox();
        lbljob = new javax.swing.JLabel();
        lblPay = new javax.swing.JLabel();
        cmbJob = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPay = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("회원 가입");

        lblId.setText("아이디");

        lblPw.setText("비밀번호");

        lblPwConfirm.setText("비밀번호 확인");

        lblName.setText("성 명");

        btnConfirm.setText("중복 확인");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnReg.setText("회원 가입");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        lblMemberType.setText("회원 구분");

        buttonGroup1.add(rbtnRegularMember);
        rbtnRegularMember.setText("정회원");
        rbtnRegularMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRegularMemberActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnAssociateMember);
        rbtnAssociateMember.setText("준회원");
        rbtnAssociateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAssociateMemberActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnStudentMember);
        rbtnStudentMember.setText("학생회원");
        rbtnStudentMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnStudentMemberActionPerformed(evt);
            }
        });

        lblInterest.setText("관심 분야");

        chkSwim.setText("수영");
        chkSwim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSwimActionPerformed(evt);
            }
        });

        chkGame.setText("게임");
        chkGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGameActionPerformed(evt);
            }
        });

        chkGolf.setText("골프");
        chkGolf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGolfActionPerformed(evt);
            }
        });

        chkSki.setText("스키");
        chkSki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSkiActionPerformed(evt);
            }
        });

        chkRead.setText("독서");
        chkRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReadActionPerformed(evt);
            }
        });

        chkTennis.setText("테니스");
        chkTennis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTennisActionPerformed(evt);
            }
        });

        lbljob.setText("직 업");

        lblPay.setText("결제 방법");

        cmbJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "학생", "대학생", "회사원", "공무원", "자영업자" }));

        lstPay.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "현금", "카드", "포인트" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstPay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId)
                                    .addComponent(lblPw)
                                    .addComponent(lblPwConfirm)
                                    .addComponent(lblName)
                                    .addComponent(lblMemberType)
                                    .addComponent(lblInterest))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtId)
                                            .addComponent(txtName)
                                            .addComponent(txtPw)
                                            .addComponent(txtPwConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnRegularMember)
                                            .addComponent(chkSwim, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkSki, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbtnAssociateMember)
                                                    .addComponent(chkGame, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chkGolf, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rbtnStudentMember)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkRead, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkTennis, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbljob)
                                    .addComponent(lblPay))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(cmbJob, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPw)
                    .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwConfirm)
                    .addComponent(txtPwConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberType)
                    .addComponent(rbtnRegularMember)
                    .addComponent(rbtnAssociateMember)
                    .addComponent(rbtnStudentMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInterest)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkSwim)
                        .addComponent(chkGame)
                        .addComponent(chkGolf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSki)
                    .addComponent(chkRead)
                    .addComponent(chkTennis))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbljob)
                    .addComponent(cmbJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReg)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(54, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //중복 확인 버튼
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        File file = new File("member.txt");
        if(!file.exists()) {
            try {
                file.createNewFile();
            } catch(IOException e) {
                e.printStackTrace();
            }
        }
        String id = txtId.getText();
        
        if(id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "아이디를 입력하세요.");
            return;
        }
        
        try(BufferedReader br = new BufferedReader(new FileReader("member.txt"))) {
            String line;
            boolean idExist = false;
            while((line=br.readLine()) != null) {
                String[] parts = line.split(" ");
                if(parts.length > 0 && parts[0].equals(id)) {
                    idExist = true;
                    break;
                }
            }
            if(idExist) {
                JOptionPane.showMessageDialog(this, "이미 존재하는 아이디입니다.");
            } else {
                JOptionPane.showMessageDialog(this, "사용 가능한 아이디입니다.");
            }
        } catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    //회원 가입 버튼
    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        String id = txtId.getText().trim();
        String name = txtName.getText().trim();        
        String password = String.valueOf(txtPw.getPassword());
        String confirmPassword = String.valueOf(txtPwConfirm.getPassword());  
        String job = (String)cmbJob.getSelectedItem();
        String pay = (String)lstPay.getSelectedValue();
        
        if(id.isEmpty() || name.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || memberType == null || job == null || pay == null) {
            JOptionPane.showMessageDialog(this, "입력하지 않은 항목이 있습니다.");
            return;
        }
        
        if(!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "비밀번호가 일치하지 않습니다.");
            return;
        }
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter("member.txt", true))) {
            String data = id + " " + password + " " + name + " " + memberType + " " + bit + " " + job + " " + pay;
            bw.write(data);
            bw.newLine();
            JOptionPane.showMessageDialog(this, "회원가입 완료.");
            clear();
            
        } catch(IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "회원가입 오류");
            clear();
        }          
    }//GEN-LAST:event_btnRegActionPerformed

    private void rbtnRegularMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRegularMemberActionPerformed
        memberType = rbtnRegularMember.getText();
    }//GEN-LAST:event_rbtnRegularMemberActionPerformed

    private void rbtnAssociateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAssociateMemberActionPerformed
        memberType = rbtnAssociateMember.getText();
    }//GEN-LAST:event_rbtnAssociateMemberActionPerformed

    private void rbtnStudentMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnStudentMemberActionPerformed
        memberType = rbtnStudentMember.getText();
    }//GEN-LAST:event_rbtnStudentMemberActionPerformed

    private void chkSwimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSwimActionPerformed
        interestBit(32);
    }//GEN-LAST:event_chkSwimActionPerformed

    private void chkGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGameActionPerformed
        interestBit(16);
    }//GEN-LAST:event_chkGameActionPerformed

    private void chkGolfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGolfActionPerformed
        interestBit(8);
    }//GEN-LAST:event_chkGolfActionPerformed

    private void chkSkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSkiActionPerformed
        interestBit(4);
    }//GEN-LAST:event_chkSkiActionPerformed

    private void chkReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReadActionPerformed
        interestBit(2);
    }//GEN-LAST:event_chkReadActionPerformed

    private void chkTennisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTennisActionPerformed
        interestBit(1);
    }//GEN-LAST:event_chkTennisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnReg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkGame;
    private javax.swing.JCheckBox chkGolf;
    private javax.swing.JCheckBox chkRead;
    private javax.swing.JCheckBox chkSki;
    private javax.swing.JCheckBox chkSwim;
    private javax.swing.JCheckBox chkTennis;
    private javax.swing.JComboBox<String> cmbJob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInterest;
    private javax.swing.JLabel lblMemberType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPay;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblPwConfirm;
    private javax.swing.JLabel lbljob;
    private javax.swing.JList<String> lstPay;
    private javax.swing.JRadioButton rbtnAssociateMember;
    private javax.swing.JRadioButton rbtnRegularMember;
    private javax.swing.JRadioButton rbtnStudentMember;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JPasswordField txtPwConfirm;
    // End of variables declaration//GEN-END:variables
}
